-- Initial data for CVE Tracker
--
-- INTENTIONALLY EMPTY.
--
-- This file previously inserted mock/demo assets, vulnerabilities and CVEs.
-- That seed data has been removed: the system must contain only real,
-- scan-discovered data (pushed via POST /api/v2/sync/cpe by Network Scanner
-- Pro). Do not re-add demo INSERT statements here.
